import io
import pandas as pd
from fpdf import FPDF
from streamlit import pdf


def create_excel_report(
    summary_df,
    feature_df,
    result_df,
    prediction_df,
    classification_report_df=None,
):
    output = io.BytesIO()

    with pd.ExcelWriter(output, engine="openpyxl") as writer:
        summary_df.to_excel(writer, sheet_name="Dataset Summary", index=False)
        feature_df.to_excel(writer, sheet_name="Feature Analysis", index=False)
        result_df.to_excel(writer, sheet_name="Model Results", index=False)
        prediction_df.to_excel(writer, sheet_name="Predictions", index=False)

        if classification_report_df is not None:
            classification_report_df.to_excel(
                writer,
                sheet_name="Classification Report"
            )

        workbook = writer.book

        for sheet_name in workbook.sheetnames:
            sheet = workbook[sheet_name]

            for cell in sheet[1]:
                cell.font = cell.font.copy(bold=True, color="FFFFFF")
                cell.fill = cell.fill.copy(
                    fill_type="solid",
                    fgColor="2563EB"
                )

            for column in sheet.columns:
                max_length = 0
                column_letter = column[0].column_letter

                for cell in column:
                    try:
                        max_length = max(max_length, len(str(cell.value)))
                    except Exception:
                        pass

                sheet.column_dimensions[column_letter].width = max_length + 3

    output.seek(0)
    return output.getvalue()


class StylishPDF(FPDF):
    def header(self):
        self.set_fill_color(37, 99, 235)
        self.rect(0, 0, 210, 28, "F")

        self.set_text_color(255, 255, 255)
        self.set_font("Arial", "B", 18)
        self.cell(0, 12, "DataSense AutoMLSS Report", ln=True, align="C")

        self.set_font("Arial", "", 10)
        self.cell(
            0,
            8,
            "AI-Powered Dataset Analyzer | AutoML | Report Generator",
            ln=True,
            align="C",
        )
        self.ln(10)

    def footer(self):
        self.set_y(-18)
        self.set_font("Arial", "I", 9)
        self.set_text_color(120, 120, 120)
        self.cell(
            0,
            10,
            "Built with love by Shoubhya Sinha | DataSense AutoMLSS",
            align="C",
        )


def add_section_title(pdf, title):
    pdf.set_fill_color(124, 58, 237)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", "B", 13)
    pdf.cell(0, 10, title, ln=True, fill=True)
    pdf.ln(4)


def add_table(pdf, df, max_rows=10, max_cols=5):
    if df is None or df.empty:
        pdf.set_text_color(80, 80, 80)
        pdf.set_font("Arial", "", 10)
        pdf.cell(0, 8, "No data available.", ln=True)
        pdf.ln(5)
        return

    df = df.head(max_rows).copy()

    if len(df.columns) > max_cols:
        df = df.iloc[:, :max_cols]

    df = df.astype(str)

    page_width = pdf.w - 20
    col_width = page_width / max(len(df.columns), 1)

    pdf.set_font("Arial", "B", 7)
    pdf.set_fill_color(37, 99, 235)
    pdf.set_text_color(255, 255, 255)

    for col in df.columns:
        pdf.cell(col_width, 8, str(col)[:14], border=1, align="C", fill=True)
    pdf.ln()

    pdf.set_font("Arial", "", 6)
    pdf.set_text_color(30, 30, 30)

    for _, row in df.iterrows():
        for value in row:
            text = str(value)
            if len(text) > 12:
                text = text[:12] + "..."
            pdf.cell(col_width, 7, text, border=1, align="C")
        pdf.ln()

    pdf.ln(5)


def create_pdf_report(
    summary_df,
    feature_df,
    result_df,
    target_column,
    task_type,
    best_model_name,
    prediction_df,
    classification_report_df=None,
):
    pdf = StylishPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=18)

    pdf.set_text_color(15, 23, 42)
    pdf.set_font("Arial", "B", 20)
    pdf.cell(0, 12, "Professional Machine Learning Report", ln=True, align="C")

    pdf.set_font("Arial", "", 11)
    pdf.set_text_color(80, 80, 80)
    pdf.multi_cell(
        0,
        8,
        "This report was automatically generated by DataSense AutoMLSS. "
        "It includes dataset summary, feature analysis, model comparison, "
        "predictions, and final machine learning outcome.",
    )
    pdf.ln(5)

    add_section_title(pdf, "1. Project Overview")

    pdf.set_font("Arial", "", 11)
    pdf.set_text_color(30, 30, 30)
    pdf.cell(0, 8, f"Target Column: {target_column}", ln=True)
    pdf.cell(0, 8, f"Problem Type: {task_type}", ln=True)
    pdf.cell(0, 8, f"Best Model Selected: {best_model_name}", ln=True)
    pdf.ln(6)

    add_section_title(pdf, "2. Dataset Summary")
    add_table(pdf, summary_df, max_rows=10, max_cols=2)

    add_section_title(pdf, "3. Feature Analysis")
    add_table(pdf, feature_df, max_rows=8, max_cols=4)

    add_section_title(pdf, "4. Model Performance Comparison")
    add_table(pdf, result_df, max_rows=10, max_cols=5)

    add_section_title(pdf, "5. Prediction Samples")
    add_table(pdf, prediction_df, max_rows=8, max_cols=5)

    if classification_report_df is not None:
        add_section_title(pdf, "6. Classification Report")
        add_table(pdf, classification_report_df.reset_index(), max_rows=10, max_cols=5)

    add_section_title(pdf, "7. Final Conclusion")

    pdf.set_font("Arial", "", 11)
    pdf.set_text_color(30, 30, 30)
    pdf.multi_cell(
        0,
        8,
        f"The selected best model for this dataset is {best_model_name}. "
        f"The project performed a complete {task_type} machine learning workflow, "
        "including data analysis, preprocessing, model training, result comparison, "
        "and report generation.",
    )

    pdf.ln(5)

    pdf.set_fill_color(37, 99, 235)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font("Arial", "B", 12)
    pdf.cell(
        0,
        10,
        "Upload -> Analyze -> Train -> Compare -> Download -> Present",
        ln=True,
        align="C",
        fill=True,
    )

    pdf_bytes = pdf.output(dest="S")

    if isinstance(pdf_bytes, str):
        pdf_bytes = pdf_bytes.encode("latin-1")
    else:
        pdf_bytes = bytes(pdf_bytes)

    return pdf_bytes